[package]
name = "adventure_game_challenge"
version = "0.1.0"
authors = ["Mattsi <mattsi@jansky.dev>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io="0.1.12"
